#!/bin/sh
# Generated by tools/build-online-installer.mjs; do not edit by hand.
# Usage: wget -qO- https://host/install-online.sh | sh

set -eu

BUNDLE_DIR="$(mktemp -d /tmp/naive-orch-install.XXXXXX)"
cleanup_bundle() { rm -rf "$BUNDLE_DIR"; }
trap cleanup_bundle 0
trap 'exit 1' 1 2 15

extract_file() {
	local relative="$1" mode="$2" target="$BUNDLE_DIR/$1"
	mkdir -p "$(dirname "$target")"
	cat > "$target"
	chmod "$mode" "$target"
}

extract_file 'install.sh' '0755' <<'__NAIVE_ORCH_FILE_0__'
#!/bin/sh
# naive-orch installer (run on the OpenWrt router).
# Copies files from ./root into /, fixes permissions, and optionally enables
# and starts the service.
#
# Usage (on the router):
#   sh install.sh            # install files and dependencies
#   sh install.sh --enable   # also enable and start the service
#   sh install.sh --enable --uot  # install sing-box and enable UDP over TCP
#   sh install.sh --skip-naive  # do not download the official naive binary
#
# Safe by design: binds only to 127.0.0.1, the sample node is disabled,
# nothing touches firewall / DNS / nftables. UDP over TCP is keyless: the
# de-side receiver is a plain socks inbound reachable only through naive.

set -e

SRC_DIR="$(cd "$(dirname "$0")" && pwd)/root"
ENABLE=0
INSTALL_NAIVE="${NAIVE_ORCH_INSTALL_NAIVE:-1}"
INSTALL_UOT="${NAIVE_ORCH_INSTALL_UOT:-0}"
PKG_UPDATED=0

for arg in "$@"; do
	case "$arg" in
		--enable) ENABLE=1 ;;
		--uot) INSTALL_UOT=1 ;;
		--skip-naive) INSTALL_NAIVE=0 ;;
		*) echo "ERROR: unknown option: $arg" >&2; exit 2 ;;
	esac
done

[ -d "$SRC_DIR" ] || { echo "ERROR: $SRC_DIR not found"; exit 1; }

msg() {
	printf '\033[1;32m%s\033[0m\n' "$1"
}

warn() {
	printf '\033[1;33mWARNING: %s\033[0m\n' "$1" >&2
}

pkg_installed() {
	if command -v apk >/dev/null 2>&1; then
		apk info -e "$1" >/dev/null 2>&1
	else
		opkg list-installed "$1" 2>/dev/null | grep -q "^$1 "
	fi
}

pkg_update_once() {
	[ "$PKG_UPDATED" = "1" ] && return 0
	msg "==> Updating OpenWrt package lists"
	if command -v apk >/dev/null 2>&1; then
		apk update
	elif command -v opkg >/dev/null 2>&1; then
		opkg update
	else
		echo "ERROR: neither apk nor opkg was found; this does not look like OpenWrt" >&2
		exit 1
	fi
	PKG_UPDATED=1
}

pkg_install() {
	pkg_update_once
	if command -v apk >/dev/null 2>&1; then
		apk add "$@"
	else
		opkg install "$@"
	fi
}

ensure_dependencies() {
	local missing=""
	pkg_installed curl || missing="$missing curl"
	pkg_installed ca-bundle || missing="$missing ca-bundle"
	pkg_installed rpcd-mod-file || missing="$missing rpcd-mod-file"
	pkg_installed luci-base || missing="$missing luci-base"
	[ "$INSTALL_NAIVE" = "1" ] && ! command -v xz >/dev/null 2>&1 && \
		missing="$missing xz-utils"

	if [ -n "$missing" ]; then
		msg "==> Installing dependencies:$missing"
		# The values above are fixed package names, not user input.
		# shellcheck disable=SC2086
		pkg_install $missing
	else
		msg "==> Dependencies are already installed"
	fi
}

download_naive() {
	local arch api_dir api_file asset_arch asset_name asset_url asset_digest
	local archive extract_dir binary

	[ "$INSTALL_NAIVE" = "1" ] || {
		warn "naive installation skipped by request"
		return 0
	}
	[ -x /usr/bin/naive ] && {
		msg "==> naive binary is already installed"
		return 0
	}

	arch=""
	[ -r /etc/openwrt_release ] && . /etc/openwrt_release
	arch="${DISTRIB_ARCH:-}"
	[ -n "$arch" ] || {
		echo "ERROR: cannot determine OpenWrt package architecture" >&2
		exit 1
	}

	api_dir="$(mktemp -d /tmp/naive-orch-naive.XXXXXX)"
	api_file="$api_dir/release.json"
	msg "==> Installing official naiveproxy binary for $arch"
	curl -fsSL --retry 3 --connect-timeout 10 \
		-o "$api_file" https://api.github.com/repos/klzgrad/naiveproxy/releases/latest

	# Prefer a static OpenWrt build when the release provides one, otherwise use
	# the exact OpenWrt architecture build. Never guess a CPU architecture.
	asset_arch="${arch}-static"
	asset_name="$(sed -n 's/.*"name": "\([^"]*openwrt-'"$asset_arch"'\.tar\.xz\)".*/\1/p' "$api_file" | head -n 1)"
	if [ -z "$asset_name" ]; then
		asset_arch="$arch"
		asset_name="$(sed -n 's/.*"name": "\([^"]*openwrt-'"$asset_arch"'\.tar\.xz\)".*/\1/p' "$api_file" | head -n 1)"
	fi
	if [ -z "$asset_name" ]; then
		rm -rf "$api_dir"
		echo "ERROR: the latest naiveproxy release has no OpenWrt build for '$arch'" >&2
		echo "Install /usr/bin/naive manually, then rerun with --skip-naive." >&2
		exit 1
	fi

	asset_url="$(sed -n 's|.*"browser_download_url": "\([^"]*/'"$asset_name"'\)".*|\1|p' "$api_file" | head -n 1)"
	asset_digest="$(awk -v wanted="\"name\": \"$asset_name\"" '
		index($0, wanted) { found=1 }
		found && /"digest": "sha256:/ {
			sub(/.*"digest": "sha256:/, ""); sub(/".*/, ""); print; exit
		}
		found && /"browser_download_url":/ { exit }
	' "$api_file")"
	[ -n "$asset_url" ] || {
		rm -rf "$api_dir"
		echo "ERROR: naiveproxy release metadata did not contain a download URL" >&2
		exit 1
	}

	archive="$api_dir/$asset_name"
	curl -fL --retry 3 --connect-timeout 10 -o "$archive" "$asset_url"
	if [ -n "$asset_digest" ]; then
		printf '%s  %s\n' "$asset_digest" "$archive" | sha256sum -c - >/dev/null || {
			rm -rf "$api_dir"
			echo "ERROR: naiveproxy archive checksum mismatch" >&2
			exit 1
		}
	fi

	extract_dir="$api_dir/unpacked"
	mkdir -p "$extract_dir"
	tar -xJf "$archive" -C "$extract_dir"
	binary="$(find "$extract_dir" -type f -name naive | head -n 1)"
	[ -n "$binary" ] && [ -s "$binary" ] || {
		rm -rf "$api_dir"
		echo "ERROR: naive binary was not found in $asset_name" >&2
		exit 1
	}
	cp "$binary" /usr/bin/naive
	chmod 0755 /usr/bin/naive
	/usr/bin/naive --version 2>/dev/null || /usr/bin/naive -version 2>/dev/null || true
	rm -rf "$api_dir"
}

download_sing_box() {
	local arch api_dir api_file package_ext package_name package_url package_digest package_file

	[ -x /usr/bin/sing-box ] && {
		msg "==> sing-box is already installed"
		return 0
	}

	# Prefer the configured OpenWrt repository. If it does not provide sing-box,
	# install the matching package from the official SagerNet release.
	if pkg_install sing-box; then
		[ -x /usr/bin/sing-box ] || {
			echo "ERROR: sing-box package installed but /usr/bin/sing-box is missing" >&2
			exit 1
		}
		return 0
	fi
	warn "sing-box is unavailable in the configured package feeds; using the official release"

	arch=""
	[ -r /etc/openwrt_release ] && . /etc/openwrt_release
	arch="${DISTRIB_ARCH:-}"
	[ -n "$arch" ] || {
		echo "ERROR: cannot determine OpenWrt package architecture for sing-box" >&2
		exit 1
	}

	if command -v apk >/dev/null 2>&1; then
		package_ext="apk"
	else
		package_ext="ipk"
	fi

	api_dir="$(mktemp -d /tmp/naive-orch-sing-box.XXXXXX)"
	api_file="$api_dir/release.json"
	curl -fsSL --retry 3 --connect-timeout 10 \
		-o "$api_file" https://api.github.com/repos/SagerNet/sing-box/releases/latest

	package_name="$(sed -n 's/.*"name": "\([^"]*_openwrt_'"$arch"'\.'"$package_ext"'\)".*/\1/p' "$api_file" | head -n 1)"
	[ -n "$package_name" ] || {
		rm -rf "$api_dir"
		echo "ERROR: the latest sing-box release has no OpenWrt package for '$arch'" >&2
		exit 1
	}

	package_url="$(sed -n 's|.*"browser_download_url": "\([^"]*/'"$package_name"'\)".*|\1|p' "$api_file" | head -n 1)"
	package_digest="$(awk -v wanted="\"name\": \"$package_name\"" '
		index($0, wanted) { found=1 }
		found && /"digest": "sha256:/ {
			sub(/.*"digest": "sha256:/, ""); sub(/".*/, ""); print; exit
		}
		found && /"browser_download_url":/ { exit }
	' "$api_file")"
	[ -n "$package_url" ] && [ -n "$package_digest" ] || {
		rm -rf "$api_dir"
		echo "ERROR: sing-box release metadata is missing URL or SHA-256" >&2
		exit 1
	}

	package_file="$api_dir/$package_name"
	curl -fL --retry 3 --connect-timeout 10 -o "$package_file" "$package_url"
	printf '%s  %s\n' "$package_digest" "$package_file" | sha256sum -c - >/dev/null || {
		rm -rf "$api_dir"
		echo "ERROR: sing-box package checksum mismatch" >&2
		exit 1
	}

	if [ "$package_ext" = "apk" ]; then
		# The package is verified against GitHub's release digest above.
		apk add --allow-untrusted "$package_file"
	else
		opkg install "$package_file"
	fi
	rm -rf "$api_dir"
	[ -x /usr/bin/sing-box ] || {
		echo "ERROR: /usr/bin/sing-box is missing after installation" >&2
		exit 1
	}
}

configure_uot() {
	[ "$INSTALL_UOT" = "1" ] || return 0

	uci set naive-orch.@global[0].udp_over_tcp='1'
	# Keyless UoT: the old SS-2022 options are no longer used by the router.
	uci -q delete naive-orch.@global[0].uot_psk 2>/dev/null || true
	uci -q delete naive-orch.@global[0].uot_method 2>/dev/null || true
	# 8388 could only mean the legacy SS receiver; the socks receiver is 8389.
	if [ "$(uci -q get naive-orch.@global[0].uot_port 2>/dev/null)" = "8388" ]; then
		uci -q delete naive-orch.@global[0].uot_port
	fi
	uci -q get naive-orch.@global[0].uot_port >/dev/null || \
		uci set naive-orch.@global[0].uot_port='8389'
	uci -q get naive-orch.@global[0].uot_offset >/dev/null || \
		uci set naive-orch.@global[0].uot_offset='1000'
	uci commit naive-orch
	chmod 0600 /etc/config/naive-orch
}

ensure_dependencies
download_naive
[ "$INSTALL_UOT" = "1" ] && download_sing_box

msg "==> Installing naive-orch from $SRC_DIR"

# /etc/config: do not clobber an existing user config
if [ -f /etc/config/naive-orch ]; then
	echo "    keep existing /etc/config/naive-orch (installing sample as .new)"
	cp "$SRC_DIR/etc/config/naive-orch" /etc/config/naive-orch.new
else
	cp "$SRC_DIR/etc/config/naive-orch" /etc/config/naive-orch
	chmod 0600 /etc/config/naive-orch
fi

cp "$SRC_DIR/etc/init.d/naive-orch" /etc/init.d/naive-orch
chmod 0755 /etc/init.d/naive-orch

mkdir -p /usr/libexec/naive-orch
for f in lib.sh render-config healthcheck status sub-update; do
	cp "$SRC_DIR/usr/libexec/naive-orch/$f" "/usr/libexec/naive-orch/$f"
done
chmod 0644 /usr/libexec/naive-orch/lib.sh
chmod 0755 /usr/libexec/naive-orch/render-config \
           /usr/libexec/naive-orch/healthcheck \
           /usr/libexec/naive-orch/status \
           /usr/libexec/naive-orch/sub-update

mkdir -p /etc/naive-orch
chmod 0700 /etc/naive-orch

# LuCI app (menu + ACL + JS views)
if [ -d "$SRC_DIR/usr/share/luci" ]; then
	echo "==> Installing LuCI app"
	mkdir -p /usr/share/luci/menu.d /usr/share/rpcd/acl.d \
	         /www/luci-static/resources/view/naive-orch
	cp "$SRC_DIR/usr/share/luci/menu.d/luci-app-naive-orch.json" /usr/share/luci/menu.d/
	cp "$SRC_DIR/usr/share/rpcd/acl.d/luci-app-naive-orch.json"  /usr/share/rpcd/acl.d/
	cp "$SRC_DIR/www/luci-static/resources/view/naive-orch/"*.js \
	   /www/luci-static/resources/view/naive-orch/
	# clear LuCI cache and reload rpcd so menu + ACL take effect
	rm -f /tmp/luci-indexcache* 2>/dev/null
	rm -rf /tmp/luci-modulecache 2>/dev/null
	/etc/init.d/rpcd restart 2>/dev/null
	echo "    LuCI: Services -> Naive Orchestrator (refresh browser)"
fi

configure_uot

msg "==> Checking installation"
[ -x /usr/bin/naive ] && echo "    naive binary: OK (/usr/bin/naive)" \
	|| warn "/usr/bin/naive is missing; nodes cannot start"
command -v curl >/dev/null 2>&1 && echo "    curl: OK"
# sing-box is only needed for variant B (UDP-over-TCP wrappers); podkop usually ships it.
if [ "$(uci -q get naive-orch.@global[0].udp_over_tcp)" = "1" ]; then
	[ -x /usr/bin/sing-box ] && echo "    sing-box: OK (UoT enabled)" \
		|| echo "    WARNING: udp_over_tcp=1 but /usr/bin/sing-box missing — UoT wrappers won't start"
	echo "    NOTE: UoT also needs a receiver on every de node — see server/uot-server-install.sh"
fi

if [ "$ENABLE" = "1" ]; then
	/etc/init.d/naive-orch enable
	/etc/init.d/naive-orch restart
	msg "==> Service enabled and started"
fi

echo ""
msg "Installation complete"
echo "Open LuCI -> Services -> Naive Orchestrator -> Settings"
echo "Add a subscription URL, save it, then update it on the Status tab."
if [ "$INSTALL_UOT" = "1" ]; then
	uot_port="$(uci -q get naive-orch.@global[0].uot_port 2>/dev/null)"
	[ -n "$uot_port" ] || uot_port='8389'
	uot_env=""
	[ "$uot_port" != "8389" ] && uot_env="SOCKS_PORT='$uot_port' "
	echo ""
	msg "UDP over TCP mode enabled (keyless)"
	echo "Run this ONE command on EVERY proxy server:"
	echo ""
	echo "  wget -qO- https://raw.githubusercontent.com/FurstFri/naive-orch/main/server/uot-server-install.sh | ${uot_env}sh"
	echo ""
	echo "The same command is shown in LuCI -> Naive Orchestrator -> Settings -> UDP over TCP."
fi
__NAIVE_ORCH_FILE_0__

extract_file 'root/etc/config/naive-orch' '0644' <<'__NAIVE_ORCH_FILE_1__'
config global
	option enabled '1'
	option bind_host '127.0.0.1'
	option health_url 'https://www.gstatic.com/generate_204'
	option check_interval '30'
	option restart_failed '1'
	# --- variant B: UDP-over-TCP (UoT), keyless ---
	# When udp_over_tcp='1', each node's public SOCKS port is served by a small
	# sing-box wrapper (TCP -> naive, UDP -> sing-box UoT v2 through that same
	# naive to the de-side socks receiver). naive itself moves to public+uot_offset.
	# No keys involved: the receiver is a plain socks inbound, firewalled to the
	# server itself and only reachable through authenticated naive.
	# Requires /usr/bin/sing-box and a UoT receiver on every de (see server/uot-server-install.sh).
	option udp_over_tcp '0'
	# de-side socks receiver port (the legacy SS receiver for phones stays on 8388)
	option uot_port '8389'
	option uot_offset '1000'

# Пример ноды. По умолчанию ВЫКЛЮЧЕНА (enabled '0').
# Заполни proxy реальными данными и поставь enabled '1'.
# Логин/пароль в URL должны быть URL-encoded.
config node 'nl'
	option enabled '0'
	option label 'naive-nl'
	option listen_port '1080'
	option proxy 'https://user:pass@nl.example.com:443'
	option concurrency '0'
__NAIVE_ORCH_FILE_1__

extract_file 'root/etc/init.d/naive-orch' '0755' <<'__NAIVE_ORCH_FILE_2__'
#!/bin/sh /etc/rc.common

# naive-orch: orchestrates one or more naiveproxy -> local SOCKS5 ports.
# Routing / DNS / selector / urltest is Podkop's job, not ours.

USE_PROCD=1
START=88
STOP=10

EXTRA_COMMANDS="check update"
EXTRA_HELP="    check     Show healthcheck status (status.json)
    update    Update subscriptions now (optional: <name>)"

. /usr/libexec/naive-orch/lib.sh

g_enabled=1
g_bind="127.0.0.1"
g_interval=30
# variant B (UDP-over-TCP) globals; uot_port is the de-side socks receiver
g_uot=0
g_uot_port=8389
g_uot_offset=1000

USED_PORTS=" "

# the global section is anonymous (type 'global'); read it via config_foreach so
# values are actually picked up (a by-name config_get would only ever hit defaults).
load_global_section() {
	local s="$1"
	config_get_bool g_enabled  "$s" enabled        1
	config_get      g_bind     "$s" bind_host      "127.0.0.1"
	config_get      g_interval "$s" check_interval 30
	config_get_bool g_uot      "$s" udp_over_tcp   0
	config_get      g_uot_port "$s" uot_port       8389
	config_get      g_uot_offset "$s" uot_offset   1000
}

load_global() {
	config_foreach load_global_section global
}

start_node() {
	local id="$1"
	local enabled port proxy label conc padding

	config_get_bool enabled "$id" enabled 1
	[ "$enabled" = "1" ] || return 0

	config_get port    "$id" listen_port
	config_get proxy   "$id" proxy
	config_get label   "$id" label "naive-$id"
	config_get conc    "$id" concurrency 0
	config_get padding "$id" padding 0

	if [ -z "$port" ] || [ -z "$proxy" ]; then
		no_log "node $id: missing listen_port or proxy, skipping"
		return 0
	fi
	if ! no_is_pos_int "$port"; then
		no_log "node $id: invalid listen_port '$port', skipping"
		return 0
	fi
	if ! no_validate_proxy "$proxy"; then
		no_log "node $id: proxy must start with https://, skipping"
		return 0
	fi
	case "$USED_PORTS" in
		*" $port "*)
			no_log "node $id: port $port already in use by another node, skipping"
			return 0 ;;
	esac
	USED_PORTS="$USED_PORTS$port "

	# variant B: a sing-box wrapper owns the public port and splits TCP/UDP;
	# naive itself moves to an internal port (public + offset). Keyless: UDP
	# rides sing-box UoT to the de-side plain socks receiver.
	if [ "$g_uot" = "1" ] && [ -x "$NO_SB_BIN" ]; then
		local inner=$((port + g_uot_offset))
		local de_host="$(no_proxy_host "$proxy")"
		no_render_node    "$id" "127.0.0.1" "$inner" "$proxy" "$conc" "$padding"
		no_render_wrapper "$id" "$g_bind" "$port" "$inner" "$de_host" "$g_uot_port"

		procd_open_instance "$id"
		procd_set_param command "$NO_BIN" "$NO_RUNDIR/$id.json"
		procd_set_param respawn 3600 5 5
		procd_set_param limits nofile="65535 65535"
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_set_param pidfile "/var/run/naive-orch-$id.pid"
		procd_close_instance

		procd_open_instance "$id-uot"
		procd_set_param command "$NO_SB_BIN" run -c "$NO_RUNDIR/$id.wrap.json"
		procd_set_param respawn 3600 5 5
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_set_param pidfile "/var/run/naive-orch-$id-uot.pid"
		procd_close_instance

		no_log "node $id ($label): UoT socks://$g_bind:$port (wrapper) -> naive 127.0.0.1:$inner -> $de_host:$g_uot_port"
		return 0
	fi

	# legacy / UoT-off: naive listens directly on the public port (TCP only).
	no_render_node "$id" "$g_bind" "$port" "$proxy" "$conc" "$padding"

	procd_open_instance "$id"
	procd_set_param command "$NO_BIN" "$NO_RUNDIR/$id.json"
	procd_set_param respawn 3600 5 5
	# naive busy-loops on accept() once it runs out of file descriptors
	# (Accept error: ERR_INSUFFICIENT_RESOURCES). procd default nofile is 1024,
	# far too low for a node carrying primary traffic — raise it.
	procd_set_param limits nofile="65535 65535"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param pidfile "/var/run/naive-orch-$id.pid"
	procd_close_instance

	no_log "node $id ($label): socks://$g_bind:$port -> up"
}

start_service() {
	config_load "$NO_CFG"
	load_global
	no_is_pos_int "$g_interval" || g_interval=30

	if [ "$g_enabled" != "1" ]; then
		no_log "globally disabled (global.enabled=0), nothing started"
		return 0
	fi
	if [ ! -x "$NO_BIN" ]; then
		no_log "naive binary not found/executable at $NO_BIN, aborting start"
		return 0
	fi

	mkdir -p "$NO_RUNDIR";    chmod 0700 "$NO_RUNDIR"
	mkdir -p "$NO_STATUSDIR"; chmod 0700 "$NO_STATUSDIR"
	rm -f "$NO_RUNDIR"/*.json 2>/dev/null

	config_foreach start_node node

	# refresh the direct-list of upstream servers (loop protection helper)
	[ -x /usr/libexec/naive-orch/sub-update ] && \
		/usr/libexec/naive-orch/sub-update --servers-only >/dev/null 2>&1

	# healthcheck as its own instance (procd does not schedule by interval)
	if [ -x /usr/libexec/naive-orch/healthcheck ]; then
		procd_open_instance "healthcheck"
		procd_set_param command /bin/sh -c \
			"while :; do /usr/libexec/naive-orch/healthcheck; sleep ${g_interval:-30}; done"
		procd_set_param respawn 3600 10 0
		procd_close_instance
	fi

	# subscription auto-update timer (decides per-subscription when to refresh)
	if [ -x /usr/libexec/naive-orch/sub-update ]; then
		procd_open_instance "subtimer"
		procd_set_param command /bin/sh -c \
			"while :; do sleep 3600; /usr/libexec/naive-orch/sub-update --timer; done"
		procd_set_param respawn 3600 10 0
		procd_close_instance
	fi
}

stop_service() {
	# Do not leave a successful-looking CLI status behind after the service was
	# explicitly stopped. LuCI also checks procd state, this keeps both views in sync.
	rm -f "$NO_STATUS" 2>/dev/null
	rmdir "$NO_HEALTHLOCK" 2>/dev/null
	return 0
}

service_triggers() {
	procd_add_reload_trigger "$NO_CFG"
}

# JSON config is regenerated on start; force a full restart on reload so
# instances pick up new configs (procd would otherwise keep them running).
reload_service() {
	stop
	start
}

check() {
	/usr/libexec/naive-orch/status
}

update() {
	/usr/libexec/naive-orch/sub-update "$1"
}
__NAIVE_ORCH_FILE_2__

extract_file 'root/usr/libexec/naive-orch/healthcheck' '0755' <<'__NAIVE_ORCH_FILE_3__'
#!/bin/sh
# Healthcheck: probe each enabled node's SOCKS port, write status.json.
# Does NOT switch routes (that is Podkop's job) and does NOT restart procd.

. /lib/functions.sh
. /usr/libexec/naive-orch/lib.sh

config_load "$NO_CFG"
HEALTH_URL="https://www.gstatic.com/generate_204"
BIND="127.0.0.1"

load_health_global() {
	local section="$1"
	config_get HEALTH_URL "$section" health_url "$HEALTH_URL"
	config_get BIND       "$section" bind_host  "$BIND"
}

# Existing installations use an anonymous `config global`, while newer/manual
# configs may name it. config_foreach handles both forms consistently.
config_foreach load_health_global global

mkdir -p "$NO_STATUSDIR"; chmod 0700 "$NO_STATUSDIR"
mkdir "$NO_HEALTHLOCK" 2>/dev/null || exit 0
tmp="$NO_STATUS.$$"
now="$(date +%s)"
fragments=""
pids=""

cleanup_healthcheck() {
	rm -f "$tmp" "$tmp".* 2>/dev/null
	rmdir "$NO_HEALTHLOCK" 2>/dev/null
}
trap cleanup_healthcheck 0
trap 'exit 1' 1 2 15

have_curl=0
command -v curl >/dev/null 2>&1 && have_curl=1

probe_node() {
	local id="$1" port="$2" label="$3" fragment="$4"
	local status err lat timing label_json err_json errfile
	errfile="$fragment.err"
	if [ "$have_curl" = "1" ]; then
		# curl measures the complete request itself. This works on BusyBox systems
		# where `date +%s%N` is unsupported (the old latency was therefore empty).
		timing="$(curl -sS -o /dev/null --max-time 10 \
			--socks5-hostname "$BIND:$port" -w '%{time_total}' \
			"$HEALTH_URL" 2>"$errfile")"
		if [ "$?" = "0" ]; then
			status="healthy"
			lat="$(LC_ALL=C awk -v seconds="$timing" 'BEGIN {
				if (seconds ~ /^[0-9]+([.][0-9]+)?$/) printf "%.0f", seconds * 1000
			}')"
		else
			status="down"
			err="$(tail -n 1 "$errfile" 2>/dev/null)"
			[ -n "$err" ] || err="curl failed"
		fi
		rm -f "$errfile"
	else
		status="unknown"; err="curl not installed"
	fi
	label_json="$(no_json_escape "$label")"
	err_json="$(no_json_escape "$err")"

	{
		printf '"%s": {\n' "$id"
		printf '    "label": "%s",\n' "$label_json"
		printf '    "status": "%s",\n' "$status"
		printf '    "port": %s,\n' "$port"
		if [ "$status" = "healthy" ] && [ -n "$lat" ]; then
			printf '    "latency_ms": %s,\n' "$lat"
		fi
		[ -n "$err_json" ] && printf '    "last_error": "%s",\n' "$err_json"
		printf '    "last_check": %s\n' "$now"
		printf '}\n'
	} > "$fragment"
}

start_node_probe() {
	local id="$1" enabled port label fragment
	config_get_bool enabled "$id" enabled 1
	[ "$enabled" = "1" ] || return 0
	config_get port  "$id" listen_port
	config_get label "$id" label "naive-$id"
	[ -n "$port" ] || return 0

	fragment="$tmp.$id"
	fragments="$fragments $fragment"
	probe_node "$id" "$port" "$label" "$fragment" &
	pids="$pids $!"
}

config_foreach start_node_probe node

# Probe nodes concurrently: a manual refresh now takes at most one curl timeout,
# rather than 10 seconds multiplied by the number of nodes.
for pid in $pids; do
	wait "$pid"
done

printf '{\n' > "$tmp"
first=1
for fragment in $fragments; do
	[ -s "$fragment" ] || continue
	[ "$first" = "1" ] || printf ',\n' >> "$tmp"
	first=0
	sed 's/^/  /' "$fragment" >> "$tmp"
done
printf '}\n' >> "$tmp"
mv "$tmp" "$NO_STATUS"
chmod 0600 "$NO_STATUS"
trap - 0 1 2 15
cleanup_healthcheck
__NAIVE_ORCH_FILE_3__

extract_file 'root/usr/libexec/naive-orch/lib.sh' '0644' <<'__NAIVE_ORCH_FILE_4__'
#!/bin/sh
# Shared helpers for naive-orch (sourced by init.d, healthcheck, status, sub-update)

NO_CFG="naive-orch"
NO_BIN="/usr/bin/naive"
NO_SB_BIN="/usr/bin/sing-box"
NO_RUNDIR="/var/etc/naive-orch"
NO_STATUSDIR="/var/run/naive-orch"
NO_STATUS="$NO_STATUSDIR/status.json"
NO_SERVERS="$NO_STATUSDIR/servers.txt"
NO_SUBOP="$NO_STATUSDIR/sub-update.json"
NO_SUBLOCK="$NO_STATUSDIR/sub-update.lock"
NO_HEALTHLOCK="$NO_STATUSDIR/healthcheck.lock"

NO_PERSIST="/etc/naive-orch"
NO_PORTMAP="$NO_PERSIST/portmap"
NO_SUBSTATE="$NO_PERSIST/sub-state"

no_log() {
	logger -t naive-orch "$@"
}

# Escape a single-line value for use in the small JSON documents produced by
# the helper scripts. UCI labels are user-controlled, so writing them verbatim
# can otherwise make the whole status response invalid.
no_json_escape() {
	printf '%s' "$1" | tr '\r\n\t' '   ' | sed 's/\\/\\\\/g; s/"/\\"/g'
}

# proxy URL must start with https://
no_validate_proxy() {
	case "$1" in
		https://*) return 0 ;;
		*)         return 1 ;;
	esac
}

# is the argument a positive integer > 0 ?
no_is_pos_int() {
	case "$1" in
		''|*[!0-9]*) return 1 ;;
		0)           return 1 ;;
		*)           return 0 ;;
	esac
}

# render one node config.json
# args: id bind_host listen_port proxy concurrency padding
no_render_node() {
	local id="$1" bind="$2" port="$3" proxy="$4" conc="$5" padding="$6"
	local f="$NO_RUNDIR/$id.json"

	{
		printf '{\n'
		printf '  "listen": "socks://%s:%s",\n' "$bind" "$port"
		if no_is_pos_int "$conc"; then
			printf '  "insecure-concurrency": %s,\n' "$conc"
		fi
		if [ "$padding" = "1" ] || [ "$padding" = "true" ]; then
			printf '  "padding": true,\n'
		fi
		printf '  "proxy": "%s"\n' "$proxy"
		printf '}\n'
	} > "$f"
	chmod 0600 "$f"
}

# render a sing-box "UoT wrapper" for one node (variant B).
# The wrapper is what Podkop talks to on the public port; it splits:
#   TCP -> the node's naive SOCKS (direct, no double tunnel)
#   UDP -> a socks outbound with sing-box UoT v2, detoured THROUGH that same
#          naive, reaching the de-side plain socks receiver at <de_host>:<uot_port>.
# No key is involved: sing-box socks inbounds unwrap UoT automatically, and the
# receiver port is firewalled so only the de itself (i.e. traffic arriving
# through authenticated naive) can reach it. Everything is already inside TLS.
# NB: the receiver target is the de's PUBLIC host (not 127.0.0.1). naive's forward_proxy denies
# CONNECT to loopback by default, and the loopback-allowing ACL breaks NaiveProxy clients
# (NekoBox). Targeting the public host hairpins into the de's own receiver (firewalled so only
# the node itself can reach :uot_port), needs NO caddy ACL, and keeps de identical for phones.
# args: id bind public_port naive_port de_host uot_port
no_render_wrapper() {
	local id="$1" bind="$2" pub="$3" inner="$4" de_host="$5" uot_port="$6"
	local f="$NO_RUNDIR/$id.wrap.json"

	cat > "$f" <<EOF
{
  "log": { "level": "warn" },
  "inbounds": [
    { "type": "mixed", "tag": "in", "listen": "$bind", "listen_port": $pub }
  ],
  "outbounds": [
    { "type": "socks", "tag": "naive", "server": "127.0.0.1", "server_port": $inner },
    { "type": "socks", "tag": "uot",
      "server": "$de_host", "server_port": $uot_port,
      "udp_over_tcp": { "enabled": true, "version": 2 }, "detour": "naive" }
  ],
  "route": { "rules": [ { "network": "udp", "action": "route", "outbound": "uot" } ], "final": "naive" }
}
EOF
	chmod 0600 "$f"
}

# extract the host from a naive proxy URL (https://user:pass@host:port -> host)
no_proxy_host() {
	local u="${1#https://}"   # strip scheme
	u="${u#*@}"               # strip userinfo
	u="${u%%:*}"              # strip :port
	u="${u%%/*}"              # strip /path
	echo "$u"
}
__NAIVE_ORCH_FILE_4__

extract_file 'root/usr/libexec/naive-orch/render-config' '0755' <<'__NAIVE_ORCH_FILE_5__'
#!/bin/sh
# render-config: (re)generate /var/etc/naive-orch/*.json for all enabled nodes,
# without touching procd. Useful for debugging / inspecting generated configs.
# Mirrors the init.d logic, including variant B (UDP-over-TCP) wrappers.

. /lib/functions.sh
. /usr/libexec/naive-orch/lib.sh

BIND="127.0.0.1"
G_UOT=0; G_UOT_PORT=8389; G_UOT_OFFSET=1000

load_g() {
	local s="$1"
	config_get      BIND         "$s" bind_host    "127.0.0.1"
	config_get_bool G_UOT        "$s" udp_over_tcp 0
	config_get      G_UOT_PORT   "$s" uot_port     8389
	config_get      G_UOT_OFFSET "$s" uot_offset   1000
}

config_load "$NO_CFG"
config_foreach load_g global

mkdir -p "$NO_RUNDIR"; chmod 0700 "$NO_RUNDIR"

render() {
	local id="$1" enabled port proxy conc padding
	config_get_bool enabled "$id" enabled 1
	[ "$enabled" = "1" ] || return 0
	config_get port    "$id" listen_port
	config_get proxy   "$id" proxy
	config_get conc    "$id" concurrency 0
	config_get padding "$id" padding 0
	[ -n "$port" ] && [ -n "$proxy" ] || return 0

	if [ "$G_UOT" = "1" ]; then
		local inner=$((port + G_UOT_OFFSET))
		local de_host="$(no_proxy_host "$proxy")"
		no_render_node    "$id" "127.0.0.1" "$inner" "$proxy" "$conc" "$padding"
		no_render_wrapper "$id" "$BIND" "$port" "$inner" "$de_host" "$G_UOT_PORT"
		echo "rendered $NO_RUNDIR/$id.json (naive 127.0.0.1:$inner) + $id.wrap.json (socks://$BIND:$port -> $de_host:$G_UOT_PORT, UoT)"
	else
		no_render_node "$id" "$BIND" "$port" "$proxy" "$conc" "$padding"
		echo "rendered $NO_RUNDIR/$id.json  (socks://$BIND:$port)"
	fi
}

config_foreach render node
__NAIVE_ORCH_FILE_5__

extract_file 'root/usr/libexec/naive-orch/status' '0755' <<'__NAIVE_ORCH_FILE_6__'
#!/bin/sh
# Print healthcheck status. Human-readable by default, raw JSON with --json.
# --refresh runs a check immediately and then returns JSON (used by LuCI).

. /usr/libexec/naive-orch/lib.sh

if [ "$1" = "--refresh" ]; then
	/usr/libexec/naive-orch/healthcheck >/dev/null 2>&1 || true
	[ -f "$NO_STATUS" ] && cat "$NO_STATUS" || echo "{}"
	exit 0
fi

if [ "$1" = "--json" ]; then
	[ -f "$NO_STATUS" ] && cat "$NO_STATUS" || echo "{}"
	exit 0
fi

if [ ! -f "$NO_STATUS" ]; then
	echo "naive-orch: no status yet (service not running, or first check pending)"
	exit 0
fi

# Pretty-print without requiring jq: parse the simple status.json we generate.
awk '
	/"[a-zA-Z0-9_]+": \{/ {
		gsub(/[",:{ ]/,""); id=$0; next
	}
	/"label":/    { gsub(/.*"label": *"/,""); gsub(/".*/,""); label=$0; next }
	/"status":/   { gsub(/.*"status": *"/,""); gsub(/".*/,""); st=$0; next }
	/"port":/     { gsub(/[^0-9]/,""); port=$0; next }
	/"latency_ms":/ { gsub(/[^0-9]/,""); lat=$0; next }
	/"last_error":/ { gsub(/.*"last_error": *"/,""); gsub(/".*/,""); err=$0; next }
	/^  \}/ {
		line = sprintf("  %-12s %-9s :%-6s", label, st, port)
		if (lat != "") line = line " " lat "ms"
		if (err != "") line = line "  (" err ")"
		print line
		label=""; st=""; port=""; lat=""; err=""
	}
' "$NO_STATUS"

if [ -f "$NO_SERVERS" ] && [ -s "$NO_SERVERS" ]; then
	echo ""
	echo "Upstream servers (add to Podkop direct / direct-DNS to avoid loops):"
	sed 's/^/  /' "$NO_SERVERS"
fi
__NAIVE_ORCH_FILE_6__

extract_file 'root/usr/libexec/naive-orch/sub-update' '0755' <<'__NAIVE_ORCH_FILE_7__'
#!/bin/sh
# sub-update: fetch naive subscriptions, parse, materialize nodes into UCI.
#
# Usage:
#   sub-update                update all enabled subscriptions (force)
#   sub-update <name>         update one subscription (force)
#   sub-update --all          update all enabled subscriptions (force)
#   sub-update --timer        update only subscriptions that are due (auto timer)
#   sub-update --servers-only just rebuild servers.txt from current UCI nodes
#   sub-update --start [name]  start a non-blocking update for LuCI
#   sub-update --status        print the current/last operation as JSON

. /lib/functions.sh
. /usr/libexec/naive-orch/lib.sh

MODE="$1"
MODE_ARG="$2"
TAKEN=""
SUB_NODES=0
SUB_ERROR=""

# ---- observable operation state ------------------------------------------

subop_write() {
	local state="$1" current="$2" completed="$3" total="$4" nodes="$5"
	local message="$6" finished="${7:-0}" tmp
	tmp="$NO_SUBOP.$$"
	{
		printf '{\n'
		printf '  "state": "%s",\n' "$(no_json_escape "$state")"
		printf '  "mode": "%s",\n' "$(no_json_escape "${OP_MODE:-all}")"
		printf '  "current": "%s",\n' "$(no_json_escape "$current")"
		printf '  "completed": %s,\n' "${completed:-0}"
		printf '  "total": %s,\n' "${total:-0}"
		printf '  "nodes": %s,\n' "${nodes:-0}"
		printf '  "message": "%s",\n' "$(no_json_escape "$message")"
		printf '  "started_at": %s,\n' "${OP_STARTED:-0}"
		printf '  "finished_at": %s\n' "$finished"
		printf '}\n'
	} > "$tmp"
	mv "$tmp" "$NO_SUBOP"
	chmod 0600 "$NO_SUBOP" 2>/dev/null
}

subop_idle() {
	printf '%s\n' '{"state":"idle","mode":"","current":"","completed":0,"total":0,"nodes":0,"message":"Обновления ещё не запускались","started_at":0,"finished_at":0}'
}

mkdir -p "$NO_STATUSDIR"
chmod 0700 "$NO_STATUSDIR" 2>/dev/null

if [ "$MODE" = "--status" ]; then
	[ -s "$NO_SUBOP" ] && cat "$NO_SUBOP" || subop_idle
	exit 0
fi

acquire_lock() {
	local oldpid
	mkdir "$NO_SUBLOCK" 2>/dev/null && return 0
	oldpid="$(cat "$NO_SUBLOCK/pid" 2>/dev/null)"
	case "$oldpid" in
		''|*[!0-9]*) return 1 ;;
	esac
	if kill -0 "$oldpid" 2>/dev/null; then
		return 1
	fi
	# A process killed with SIGKILL cannot run its trap. Recover that stale lock.
	rm -f "$NO_SUBLOCK/pid" 2>/dev/null
	rmdir "$NO_SUBLOCK" 2>/dev/null || return 1
	mkdir "$NO_SUBLOCK" 2>/dev/null
}

# LuCI starts the potentially slow network operation in the background, then
# polls --status. mkdir is an atomic lock and prevents manual/automatic runs
# from changing UCI at the same time.
if [ "$MODE" = "--start" ]; then
	target="${MODE_ARG:---all}"
	case "$target" in
		--all) ;;
		''|*[!A-Za-z0-9_]*) echo "invalid subscription name" >&2; exit 2 ;;
		*) ;;
	esac
	if ! acquire_lock; then
		echo "subscription update is already running" >&2
		exit 3
	fi
	echo "$$" > "$NO_SUBLOCK/pid"
	OP_STARTED="$(date +%s)"
	OP_MODE="$target"
	subop_write "running" "" 0 0 0 "Запуск обновления подписок"
	NO_SUBUPDATE_LOCKED=1 NO_SUBUPDATE_STARTED="$OP_STARTED" \
		"$0" --run "$target" >/tmp/naive-orch-sub-update.log 2>&1 &
	[ -d "$NO_SUBLOCK" ] && echo "$!" > "$NO_SUBLOCK/pid" 2>/dev/null
	printf '{"accepted":true,"pid":%s}\n' "$!"
	exit 0
fi

if [ "$MODE" = "--run" ]; then
	MODE="${MODE_ARG:---all}"
fi

LOCK_CLEANUP=0
if [ "$NO_SUBUPDATE_LOCKED" = "1" ]; then
	LOCK_CLEANUP=1
else
	if ! acquire_lock; then
		echo "subscription update is already running" >&2
		exit 3
	fi
	echo "$$" > "$NO_SUBLOCK/pid"
	LOCK_CLEANUP=1
fi

cleanup_lock() {
	[ "$LOCK_CLEANUP" = "1" ] && rm -f "$NO_SUBLOCK/pid" 2>/dev/null
	[ "$LOCK_CLEANUP" = "1" ] && rmdir "$NO_SUBLOCK" 2>/dev/null
}
trap cleanup_lock 0
trap 'exit 1' 1 2 15

OP_STARTED="${NO_SUBUPDATE_STARTED:-$(date +%s)}"
OP_MODE="${MODE:-all}"

# ---- helpers --------------------------------------------------------------

no_sid() {
	echo "$1" | sed 's/[^A-Za-z0-9_]/_/g'
}

no_hostport() {
	local u="${1#https://}"
	u="${u%%\?*}"; u="${u%%#*}"; u="${u##*@}"
	echo "$u"
}

# host:port from an https:// url (default port 443)
no_url_hostport() {
	local u="${1#https://}"; u="${u%%/*}"
	case "$u" in *:*) echo "$u" ;; *) echo "$u:443" ;; esac
}

# fetch_url <url> [resolve_ip]
# resolve_ip pins the URL host to a specific IP (curl --resolve), useful when the
# subscription domain points at this router's own public IP but the panel lives
# on an internal host (DNAT). TLS is still fully verified against the domain.
fetch_url() {
	local url="$1" rip="$2" resolve=""
	[ -n "$rip" ] && resolve="--resolve $(no_url_hostport "$url"):$rip"
	if command -v curl >/dev/null 2>&1; then
		curl -sS -L --max-time 25 $resolve "$url" 2>/dev/null
	elif command -v uclient-fetch >/dev/null 2>&1; then
		uclient-fetch -qO - "$url" 2>/dev/null
	else
		wget -qO - "$url" 2>/dev/null
	fi
}

# stdin -> decoded list of "naive+https://..." lines (handles base64 / plaintext)
decode_body() {
	local data b pad
	data="$(cat)"
	case "$data" in
		*naive+https://*) printf '%s\n' "$data" | tr -d '\r'; return 0 ;;
	esac
	b="$(printf '%s' "$data" | tr -d '\r\n\t ' | tr '_-' '/+')"
	pad=$(( ${#b} % 4 ))
	[ "$pad" = "2" ] && b="${b}=="
	[ "$pad" = "3" ] && b="${b}="
	printf '%s' "$b" | base64 -d 2>/dev/null \
		|| printf '%s' "$b" | openssl base64 -d -A 2>/dev/null
}

# parse one "naive+https://user:pass@host:port?query#label" line
# sets globals: PROXY LABEL PADDING HOSTPORT
parse_line() {
	local u frag query hostport
	u="${1#naive+}"
	frag=""; case "$u" in *#*) frag="${u##*#}"; u="${u%%#*}" ;; esac
	query=""; case "$u" in *\?*) query="${u#*\?}"; u="${u%%\?*}" ;; esac
	PROXY="$u"
	LABEL="$frag"
	PADDING=0; case "$query" in *padding=true*) PADDING=1 ;; esac
	hostport="${u#https://}"; HOSTPORT="${hostport##*@}"
}

# ---- port map (stable label -> port across updates) -----------------------

port_is_taken() {
	local p="$1"
	case " $TAKEN " in *" $p "*) return 0 ;; esac
	awk -v port="$p" '$2==port{f=1} END{exit !f}' "$NO_PORTMAP" 2>/dev/null && return 0
	return 1
}

portmap_get() {
	local key="$1" base="$2" p
	touch "$NO_PORTMAP"
	p="$(awk -v k="$key" '$1==k{print $2; exit}' "$NO_PORTMAP" 2>/dev/null)"
	if [ -n "$p" ]; then echo "$p"; return 0; fi
	p="$base"
	while port_is_taken "$p"; do p=$(( p + 1 )); done
	printf '%s %s\n' "$key" "$p" >> "$NO_PORTMAP"
	echo "$p"
}

collect_manual_port() {
	local id="$1" src port
	config_get src "$id" source ""
	[ -n "$src" ] && return 0
	config_get port "$id" listen_port
	[ -n "$port" ] && TAKEN="$TAKEN $port"
}

# ---- servers.txt (loop-protection helper) ---------------------------------

collect_server() {
	local id="$1" enabled proxy
	config_get_bool enabled "$id" enabled 1
	[ "$enabled" = "1" ] || return 0
	config_get proxy "$id" proxy
	[ -n "$proxy" ] && no_hostport "$proxy" >> "$NO_SERVERS.tmp"
}

rebuild_servers() {
	config_load "$NO_CFG"
	mkdir -p "$NO_STATUSDIR"; chmod 0700 "$NO_STATUSDIR" 2>/dev/null
	: > "$NO_SERVERS.tmp"
	config_foreach collect_server node
	sort -u "$NO_SERVERS.tmp" > "$NO_SERVERS" 2>/dev/null
	rm -f "$NO_SERVERS.tmp"
	chmod 0600 "$NO_SERVERS" 2>/dev/null
}

# ---- subscription timer state --------------------------------------------

sub_due() {
	local name="$1" auto interval last now
	config_get_bool auto "$name" auto_update 1
	[ "$auto" = "1" ] || return 1
	config_get interval "$name" update_interval 12
	no_is_pos_int "$interval" || return 1
	last="$(awk -v k="$name" '$1==k{print $2; exit}' "$NO_SUBSTATE" 2>/dev/null)"
	[ -n "$last" ] || return 0
	now="$(date +%s)"
	[ "$(( now - last ))" -ge "$(( interval * 3600 ))" ] && return 0
	return 1
}

state_set() {
	local name="$1" now
	now="$(date +%s)"
	touch "$NO_SUBSTATE"
	grep -v "^$name " "$NO_SUBSTATE" > "$NO_SUBSTATE.tmp" 2>/dev/null
	printf '%s %s\n' "$name" "$now" >> "$NO_SUBSTATE.tmp"
	mv "$NO_SUBSTATE.tmp" "$NO_SUBSTATE"
}

# ---- delete previously imported nodes of a subscription -------------------

del_sub_nodes() {
	local name="$1" s
	for s in $(uci -q show "$NO_CFG" | sed -n "s/^$NO_CFG\.\([^.]*\)\.source='sub:$name'\$/\1/p"); do
		uci -q delete "$NO_CFG.$s"
	done
}

# ---- update one subscription ----------------------------------------------

do_sub() {
	local name="$1" enabled url base conc prefix resolve raw body n
	SUB_NODES=0
	SUB_ERROR=""
	config_get_bool enabled "$name" enabled 1
	[ "$enabled" = "1" ] || {
		SUB_ERROR="подписка выключена"
		no_log "sub $name: disabled, skip"
		return 1
	}
	config_get url     "$name" url
	config_get base    "$name" base_port 1100
	config_get conc    "$name" concurrency 0
	config_get prefix  "$name" label_prefix "$name"
	config_get resolve "$name" resolve ""
	[ -n "$url" ] || {
		SUB_ERROR="не задан URL подписки"
		no_log "sub $name: no url, skip"
		return 1
	}
	if ! no_is_pos_int "$base" || [ "$base" -gt 65535 ]; then
		SUB_ERROR="некорректный базовый порт"
		no_log "sub $name: invalid base port '$base'"
		return 1
	fi

	if ! raw="$(fetch_url "$url" "$resolve")"; then
		SUB_ERROR="не удалось загрузить подписку"
		no_log "sub $name: download failed"
		return 1
	fi
	if ! body="$(printf '%s' "$raw" | decode_body)"; then
		SUB_ERROR="ответ не является списком naive или корректным base64"
		no_log "sub $name: decode failed"
		return 1
	fi
	n="$(printf '%s\n' "$body" | grep -c '^naive+https://')"
	if [ "${n:-0}" -lt 1 ]; then
		SUB_ERROR="в подписке не найдены naive-узлы"
		no_log "sub $name: fetched but no naive+ nodes parsed"
		return 1
	fi

	TAKEN=""
	config_foreach collect_manual_port node

	del_sub_nodes "$name"

	printf '%s\n' "$body" | while IFS= read -r line; do
		case "$line" in naive+https://*) ;; *) continue ;; esac
		parse_line "$line"
		[ -n "$LABEL" ] || LABEL="node"
		local port sid
		port="$(portmap_get "$name/$(no_sid "$LABEL")" "$base")"
		sid="$(no_sid "sub_${name}_${LABEL}")"
		uci -q delete "$NO_CFG.$sid"
		uci set "$NO_CFG.$sid=node"
		uci set "$NO_CFG.$sid.source=sub:$name"
		uci set "$NO_CFG.$sid.managed=1"
		uci set "$NO_CFG.$sid.enabled=1"
		uci set "$NO_CFG.$sid.label=${prefix}-${LABEL}"
		uci set "$NO_CFG.$sid.listen_port=$port"
		uci set "$NO_CFG.$sid.proxy=$PROXY"
		[ "$PADDING" = "1" ] && uci set "$NO_CFG.$sid.padding=1"
		no_is_pos_int "$conc" && uci set "$NO_CFG.$sid.concurrency=$conc"
		no_log "sub $name: + ${prefix}-${LABEL} :$port ($HOSTPORT)"
	done

	no_log "sub $name: parsed $n node(s)"
	SUB_NODES="$n"
	return 0
}

# ---- dispatch -------------------------------------------------------------

mkdir -p "$NO_PERSIST"
chmod 0700 "$NO_PERSIST" 2>/dev/null

if [ "$MODE" = "--servers-only" ]; then
	rebuild_servers
	exit 0
fi

config_load "$NO_CFG"

CHANGED=0
TOTAL=0
COMPLETED=0
UPDATED=0
FAILED=0
TOTAL_NODES=0
LAST_ERROR=""

sub_selected() {
	local name="$1" enabled
	case "$MODE" in
		--timer) sub_due "$name" ;;
		--all|'')
			config_get_bool enabled "$name" enabled 1
			[ "$enabled" = "1" ]
			;;
		*) [ "$name" = "$MODE" ] ;;
	esac
}

count_sub() {
	local name="$1"
	sub_selected "$name" || return 0
	TOTAL=$(( TOTAL + 1 ))
}

config_foreach count_sub subscription

# "Nothing is due" is the normal hourly timer case, not a failed user action.
# Keep the previous visible result instead of replacing it with a red error.
if [ "$MODE" = "--timer" ] && [ "$TOTAL" -eq 0 ]; then
	no_log "subscription timer: nothing due"
	trap - 0 1 2 15
	cleanup_lock
	exit 0
fi

subop_write "running" "" 0 "$TOTAL" 0 "Подготовка обновления подписок"

process_sub() {
	local name="$1"
	sub_selected "$name" || return 0
	subop_write "running" "$name" "$COMPLETED" "$TOTAL" "$TOTAL_NODES" \
		"Загрузка подписки $name"
	if do_sub "$name"; then
		state_set "$name"
		CHANGED=1
		UPDATED=$(( UPDATED + 1 ))
		TOTAL_NODES=$(( TOTAL_NODES + SUB_NODES ))
	else
		FAILED=$(( FAILED + 1 ))
		LAST_ERROR="$name: ${SUB_ERROR:-update failed}"
	fi
	COMPLETED=$(( COMPLETED + 1 ))
	subop_write "running" "" "$COMPLETED" "$TOTAL" "$TOTAL_NODES" \
		"Обработано подписок: $COMPLETED из $TOTAL"
}

config_foreach process_sub subscription

if [ "$CHANGED" = "1" ]; then
	subop_write "applying" "" "$COMPLETED" "$TOTAL" "$TOTAL_NODES" \
		"Сохранение узлов и перезапуск сервиса"
	if ! uci commit "$NO_CFG"; then
		subop_write "error" "" "$COMPLETED" "$TOTAL" "$TOTAL_NODES" \
			"Не удалось сохранить UCI-конфигурацию" "$(date +%s)"
		exit 1
	fi
	if ! rebuild_servers; then
		subop_write "error" "" "$COMPLETED" "$TOTAL" "$TOTAL_NODES" \
			"Конфигурация сохранена, но не удалось обновить список серверов" "$(date +%s)"
		exit 1
	fi
	if ! /etc/init.d/naive-orch reload >/dev/null 2>&1; then
		subop_write "error" "" "$COMPLETED" "$TOTAL" "$TOTAL_NODES" \
			"Узлы сохранены, но сервис не удалось перезапустить" "$(date +%s)"
		exit 1
	fi
	no_log "subscriptions updated, service reloaded"
	if [ "$FAILED" -gt 0 ]; then
		subop_write "error" "" "$COMPLETED" "$TOTAL" "$TOTAL_NODES" \
			"Обновлено подписок: $UPDATED; ошибка: $LAST_ERROR" "$(date +%s)"
		exit 1
	fi
	subop_write "success" "" "$COMPLETED" "$TOTAL" "$TOTAL_NODES" \
		"Обновлено подписок: $UPDATED; импортировано узлов: $TOTAL_NODES" "$(date +%s)"
	trap - 0 1 2 15
	cleanup_lock
	exit 0
elif [ "$TOTAL" -eq 0 ]; then
	LAST_ERROR="Нет подходящих включённых подписок"
	subop_write "error" "" 0 0 0 "$LAST_ERROR" "$(date +%s)"
	no_log "no subscriptions selected (mode=${MODE:-all})"
else
	subop_write "error" "" "$COMPLETED" "$TOTAL" 0 \
		"${LAST_ERROR:-Ни одна подписка не обновлена}" "$(date +%s)"
	no_log "no subscriptions updated (mode=${MODE:-all})"
fi

trap - 0 1 2 15
cleanup_lock
exit 1
__NAIVE_ORCH_FILE_7__

extract_file 'root/usr/share/luci/menu.d/luci-app-naive-orch.json' '0644' <<'__NAIVE_ORCH_FILE_8__'
{
	"admin/services/naive-orch": {
		"title": "Naive Orchestrator",
		"order": 60,
		"action": {
			"type": "view",
			"path": "naive-orch/overview"
		},
		"depends": {
			"acl": [ "luci-app-naive-orch" ]
		}
	},
	"admin/services/naive-orch/overview": {
		"title": "Status",
		"order": 1,
		"action": {
			"type": "view",
			"path": "naive-orch/overview"
		}
	},
	"admin/services/naive-orch/settings": {
		"title": "Settings",
		"order": 2,
		"action": {
			"type": "view",
			"path": "naive-orch/settings"
		}
	}
}
__NAIVE_ORCH_FILE_8__

extract_file 'root/usr/share/rpcd/acl.d/luci-app-naive-orch.json' '0644' <<'__NAIVE_ORCH_FILE_9__'
{
	"luci-app-naive-orch": {
		"description": "Grant UCI and RPC access to LuCI app naive-orch",
		"read": {
			"file": {
				"/var/run/naive-orch/status.json": [ "read" ],
				"/var/run/naive-orch/servers.txt": [ "read" ],
				"/usr/libexec/naive-orch/status": [ "exec" ],
				"/usr/libexec/naive-orch/sub-update": [ "exec" ],
				"/etc/init.d/naive-orch": [ "exec" ]
			},
			"ubus": {
				"service": [ "list" ]
			},
			"uci": [ "naive-orch" ]
		},
		"write": {
			"file": {
				"/usr/libexec/naive-orch/sub-update": [ "exec" ],
				"/etc/init.d/naive-orch": [ "exec" ]
			},
			"uci": [ "naive-orch" ]
		}
	}
}
__NAIVE_ORCH_FILE_9__

extract_file 'root/www/luci-static/resources/view/naive-orch/overview.js' '0644' <<'__NAIVE_ORCH_FILE_10__'
'use strict';
'require view';
'require fs';
'require dom';
'require ui';
'require poll';
'require uci';

var STATUS_CMD = '/usr/libexec/naive-orch/status';
var SUB_CMD = '/usr/libexec/naive-orch/sub-update';
var INIT_CMD = '/etc/init.d/naive-orch';
var SERVERS = '/var/run/naive-orch/servers.txt';

function parseExecJson(result) {
	if (!result || result.code !== 0)
		throw new Error((result && result.stderr) || _('Команда завершилась с ошибкой'));

	try {
		return JSON.parse(result.stdout || '{}');
	}
	catch (e) {
		throw new Error(_('Получен некорректный ответ от сервиса'));
	}
}

function readStatus(refresh) {
	return fs.exec(STATUS_CMD, [ refresh ? '--refresh' : '--json' ])
		.then(parseExecJson);
}

function readOperation() {
	return fs.exec(SUB_CMD, [ '--status' ]).then(parseExecJson);
}

function serviceRunning() {
	return fs.exec(INIT_CMD, [ 'running' ]).then(function(result) {
		return result.code === 0;
	}).catch(function() {
		return false;
	});
}

function badge(status, labels) {
	var colors = {
		healthy: '#2e7d32', down: '#c62828', degraded: '#ef6c00',
		unknown: '#777', running: '#1565c0', applying: '#6a1b9a',
		success: '#2e7d32', error: '#c62828', idle: '#777'
	};
	return E('span', {
		'style': 'display:inline-block;color:#fff;background:' + (colors[status] || '#777') +
			';padding:3px 9px;border-radius:12px;font-size:90%;white-space:nowrap'
	}, (labels && labels[status]) || status || _('неизвестно'));
}

function formatTime(epoch) {
	if (!epoch)
		return '—';
	try {
		return new Date(epoch * 1000).toLocaleString();
	}
	catch (e) {
		return String(epoch);
	}
}

function renderStatus(data, running) {
	var labels = {
		healthy: _('работает'), down: _('не отвечает'),
		degraded: _('нестабильно'), unknown: _('неизвестно')
	};

	if (!running)
		return E('div', { 'class': 'alert-message warning' }, [
			E('strong', {}, _('Сервис остановлен. ')),
			_('Нажмите «Запустить», чтобы поднять SOCKS-прокси и проверки.')
		]);

	var ids = Object.keys(data || {}).filter(function(id) {
		return id.charAt(0) !== '_';
	});

	if (!ids.length)
		return E('div', { 'class': 'alert-message notice' }, [
			E('strong', {}, _('Пока нет результатов. ')),
			_('Добавьте узел или подписку в настройках, затем запустите проверку.')
		]);

	var healthy = 0;
	var tbl = E('table', { 'class': 'table' }, [
		E('tr', { 'class': 'tr table-titles' }, [
			E('th', { 'class': 'th' }, _('Узел')),
			E('th', { 'class': 'th' }, _('Состояние')),
			E('th', { 'class': 'th' }, _('SOCKS')),
			E('th', { 'class': 'th' }, _('Задержка')),
			E('th', { 'class': 'th' }, _('Проверено')),
			E('th', { 'class': 'th' }, _('Ошибка'))
		])
	]);

	ids.sort().forEach(function(id) {
		var node = data[id] || {};
		if (node.status === 'healthy')
			healthy++;
		tbl.appendChild(E('tr', { 'class': 'tr' }, [
			E('td', { 'class': 'td' }, [
				E('strong', {}, node.label || id),
				(node.label && node.label !== id) ? E('div', { 'style': 'color:#888;font-size:90%' }, id) : ''
			]),
			E('td', { 'class': 'td' }, badge(node.status, labels)),
			E('td', { 'class': 'td' }, '127.0.0.1:' + (node.port != null ? node.port : '—')),
			E('td', { 'class': 'td' }, node.latency_ms != null ? node.latency_ms + ' мс' : '—'),
			E('td', { 'class': 'td' }, formatTime(node.last_check)),
			E('td', { 'class': 'td' }, node.last_error || '—')
		]));
	});

	return E('div', {}, [
		E('p', { 'style': 'margin:.2em 0 1em' },
			_('Доступно узлов: %s из %s').format(healthy, ids.length)),
		tbl
	]);
}

function operationText(op) {
	var total = Number(op.total || 0);
	var completed = Number(op.completed || 0);
	var nodes = Number(op.nodes || 0);

	if (op.state === 'running')
		return op.current
			? _('Загружается «%s» — %s из %s').format(op.current, completed + 1, total || '?')
			: (op.message || _('Подготовка обновления…'));
	if (op.state === 'applying')
		return _('Сохраняются %s узлов и перезапускается сервис…').format(nodes);
	if (op.state === 'success')
		return _('Готово: обработано подписок — %s, импортировано узлов — %s.').format(completed, nodes);
	if (op.state === 'error')
		return op.message || _('Обновление завершилось с ошибкой.');
	return _('Обновления ещё не запускались.');
}

function renderOperation(op) {
	op = op || { state: 'idle' };
	var labels = {
		idle: _('ожидание'), running: _('обновление'), applying: _('применение'),
		success: _('готово'), error: _('ошибка')
	};
	var busy = op.state === 'running' || op.state === 'applying';
	var total = Number(op.total || 0);
	var completed = Number(op.completed || 0);
	var children = [
		E('div', { 'style': 'display:flex;gap:.7em;align-items:center;flex-wrap:wrap' }, [
			badge(op.state || 'idle', labels),
			E('span', {}, operationText(op))
		])
	];

	if (busy && total > 0)
		children.push(E('progress', {
			'value': Math.min(completed, total),
			'max': total,
			'style': 'width:100%;margin-top:.8em'
		}));

	if (!busy && op.finished_at)
		children.push(E('div', { 'style': 'color:#777;margin-top:.5em;font-size:90%' },
			_('Завершено: %s').format(formatTime(op.finished_at))));

	return E('div', {}, children);
}

function commandError(result) {
	return new Error((result && (result.stderr || result.stdout)) || _('Команда завершилась с ошибкой'));
}

return view.extend({
	load: function() {
		return Promise.all([
			readStatus(false).catch(function() { return {}; }),
			readOperation().catch(function() { return { state: 'idle' }; }),
			fs.read(SERVERS).catch(function() { return ''; }),
			uci.load('naive-orch'),
			serviceRunning()
		]);
	},

	render: function(data) {
		var statusData = data[0] || {};
		var operation = data[1] || { state: 'idle' };
		var running = data[4];
		var statusBox = E('div', {}, renderStatus(statusData, running));
		var operationBox = E('div', {}, renderOperation(operation));
		var serviceBadge = E('span', {}, badge(running ? 'healthy' : 'down', {
			healthy: _('сервис запущен'), down: _('сервис остановлен')
		}));
		var serversBox = E('pre', {}, (data[2] || '').trim() || _('(список пуст)'));

		var g = (uci.sections('naive-orch', 'global') || [])[0] || {};
		var uotOn = g.udp_over_tcp === '1';
		var uotBadge = badge(uotOn ? 'running' : 'idle', {
			running: _('UDP over TCP включён'), idle: _('UDP over TCP выключен')
		});

		var startButton = E('button', { 'class': 'btn cbi-button cbi-button-apply' }, _('Запустить'));
		var stopButton = E('button', { 'class': 'btn cbi-button cbi-button-reset' }, _('Остановить'));
		var restartButton = E('button', { 'class': 'btn cbi-button cbi-button-action' }, _('Перезапустить'));
		var checkButton = E('button', { 'class': 'btn cbi-button cbi-button-neutral' }, _('Проверить сейчас'));
		var updateButton = E('button', { 'class': 'btn cbi-button cbi-button-apply' }, _('Обновить все подписки'));

		function setRunning(value) {
			running = value;
			dom.content(serviceBadge, badge(running ? 'healthy' : 'down', {
				healthy: _('сервис запущен'), down: _('сервис остановлен')
			}));
			startButton.disabled = running;
			stopButton.disabled = !running;
			restartButton.disabled = !running;
		}

		function setOperation(value) {
			operation = value || { state: 'idle' };
			dom.content(operationBox, renderOperation(operation));
			updateButton.disabled = operation.state === 'running' || operation.state === 'applying';
		}

		function runService(command) {
			startButton.disabled = stopButton.disabled = restartButton.disabled = true;
			return fs.exec(INIT_CMD, [ command ]).then(function(result) {
				if (result.code !== 0)
					throw commandError(result);
				ui.addNotification(null, E('p', {}, _('Команда «%s» выполнена.').format(command)), 'info');
				return Promise.all([ readStatus(false).catch(function() { return {}; }), serviceRunning() ]);
			}).then(function(result) {
				statusData = result[0];
				setRunning(result[1]);
				dom.content(statusBox, renderStatus(statusData, running));
			}).catch(function(error) {
				ui.addNotification(null, E('p', {}, error.message || String(error)), 'error');
				return serviceRunning().then(setRunning);
			});
		}

		startButton.addEventListener('click', function() { return runService('start'); });
		stopButton.addEventListener('click', function() { return runService('stop'); });
		restartButton.addEventListener('click', function() { return runService('restart'); });

		checkButton.addEventListener('click', function() {
			checkButton.disabled = true;
			checkButton.textContent = _('Проверяется…');
			return readStatus(true).then(function(result) {
				statusData = result;
				dom.content(statusBox, renderStatus(statusData, running));
			}).catch(function(error) {
				ui.addNotification(null, E('p', {}, error.message || String(error)), 'error');
			}).then(function() {
				checkButton.disabled = false;
				checkButton.textContent = _('Проверить сейчас');
			});
		});

		updateButton.addEventListener('click', function() {
			updateButton.disabled = true;
			dom.content(operationBox, renderOperation({ state: 'running', total: 0 }));
			return fs.exec(SUB_CMD, [ '--start', '--all' ]).then(function(result) {
				if (result.code !== 0)
					throw commandError(result);
				return readOperation();
			}).then(setOperation).catch(function(error) {
				ui.addNotification(null, E('p', {}, error.message || String(error)), 'error');
				return readOperation().then(setOperation);
			});
		});

		setRunning(running);
		setOperation(operation);

		poll.add(function() {
			return Promise.all([
				readStatus(false).catch(function() { return statusData; }),
				readOperation().catch(function() { return operation; }),
				serviceRunning(),
				fs.read(SERVERS).catch(function() { return ''; })
			]).then(function(result) {
				statusData = result[0];
				setOperation(result[1]);
				setRunning(result[2]);
				dom.content(statusBox, renderStatus(statusData, running));
				dom.content(serversBox, (result[3] || '').trim() || _('(список пуст)'));
			});
		}, 3);

		return E('div', {}, [
			E('div', { 'style': 'display:flex;align-items:center;justify-content:space-between;gap:1em;flex-wrap:wrap' }, [
				E('h2', { 'style': 'margin-bottom:.4em' }, _('Naive Orchestrator')),
				E('div', { 'style': 'display:flex;gap:.5em;flex-wrap:wrap' }, [ serviceBadge, uotBadge ])
			]),

			E('div', { 'class': 'cbi-section' }, [
				E('h3', {}, _('Состояние узлов')),
				E('div', { 'style': 'display:flex;gap:.5em;flex-wrap:wrap;margin-bottom:1em' }, [
					startButton, stopButton, restartButton, checkButton,
					E('a', {
						'class': 'btn cbi-button cbi-button-neutral',
						'href': L.url('admin/services/naive-orch/settings')
					}, _('Настройки'))
				]),
				statusBox
			]),

			E('div', { 'class': 'cbi-section' }, [
				E('h3', {}, _('Обновление подписок')),
				E('p', {}, _('Обновление выполняется в фоне. Эту страницу можно не держать открытой — итог сохранится до перезагрузки роутера.')),
				E('div', { 'style': 'margin-bottom:1em' }, updateButton),
				operationBox
			]),

			E('div', { 'class': 'cbi-section' }, [
				E('h3', {}, _('Защита от зацикливания')),
				E('p', {}, _('Добавьте эти серверы в Podkop как direct-маршруты и direct-DNS, иначе трафик может попасть в петлю:')),
				serversBox
			])
		]);
	},

	handleSave: null,
	handleSaveApply: null,
	handleReset: null
});
__NAIVE_ORCH_FILE_10__

extract_file 'root/www/luci-static/resources/view/naive-orch/settings.js' '0644' <<'__NAIVE_ORCH_FILE_11__'
'use strict';
'require view';
'require form';
'require fs';
'require ui';
'require uci';

var SUB_CMD = '/usr/libexec/naive-orch/sub-update';
var UOT_SERVER_URL = 'https://raw.githubusercontent.com/FurstFri/naive-orch/main/server/uot-server-install.sh';

function maskProxy(proxy) {
	return (proxy || '').replace(/\/\/[^@]*@/, '//***@');
}

/* The single command to paste on every proxy server. Non-default values are
   passed explicitly; with the default port it is just "| sh". */
function uotServerCommand(socksPort) {
	var env = '';
	if (socksPort && socksPort !== '8389')
		env += "SOCKS_PORT='" + socksPort + "' ";
	return 'wget -qO- ' + UOT_SERVER_URL + ' | ' + env + 'sh';
}

function validateHttpUrl(sectionId, value) {
	if (!/^https?:\/\/\S+$/.test(value || ''))
		return _('Введите полный URL, начинающийся с http:// или https://');
	return true;
}

function validateNaiveProxy(sectionId, value) {
	if (!/^https:\/\/\S+$/.test(value || ''))
		return _('Naive URL должен начинаться с https://');
	return true;
}

function startSubscriptionUpdate(sectionId) {
	return fs.exec(SUB_CMD, [ '--start', sectionId ]).then(function(result) {
		if (result.code !== 0)
			throw new Error(result.stderr || result.stdout || _('Не удалось запустить обновление'));

		ui.addNotification(null, E('p', {}, [
			_('Обновление «%s» запущено. Ход операции показан на вкладке ').format(sectionId),
			E('a', { 'href': L.url('admin/services/naive-orch/overview') }, _('Статус')),
			'.'
		]), 'info');
	}).catch(function(error) {
		ui.addNotification(null, E('p', {}, error.message || String(error)), 'error');
	});
}

return view.extend({
	load: function() {
		return uci.load('naive-orch');
	},

	render: function() {
		var m, s, o;

		m = new form.Map('naive-orch', _('Настройки Naive Orchestrator'),
			_('Обычно достаточно добавить URL подписки. Naive Orchestrator создаёт локальные SOCKS5-порты, а маршрутизацией и DNS продолжает управлять Podkop.'));

		/* ---------------- global: simple first, advanced out of the way -------- */
		s = m.section(form.TypedSection, 'global', _('Основные настройки'));
		s.anonymous = true;
		s.addremove = false;

		s.tab('basic', _('Основное'),
			_('Этих параметров достаточно для обычной установки.'));
		s.tab('advanced', _('Дополнительно'),
			_('Меняйте эти параметры только если понимаете, зачем они нужны.'));
		s.tab('uot', _('UDP over TCP'),
			_('Включите режим и выполните показанную команду на каждом внешнем сервере — больше ничего настраивать не нужно.'));

		o = s.taboption('basic', form.Flag, 'enabled', _('Включить сервис'),
			_('Главный выключатель всех узлов и фоновых проверок.'));
		o.default = '1';
		o.rmempty = false;

		o = s.taboption('basic', form.Value, 'check_interval', _('Проверять узлы каждые'),
			_('Интервал автоматической проверки доступности и задержки, в секундах.'));
		o.datatype = 'range(10,3600)';
		o.default = '30';
		o.placeholder = '30';

		o = s.taboption('advanced', form.Value, 'bind_host', _('Адрес SOCKS'),
			_('Оставьте 127.0.0.1, чтобы прокси был доступен только самому роутеру.'));
		o.datatype = 'ipaddr';
		o.default = '127.0.0.1';
		o.rmempty = false;

		o = s.taboption('advanced', form.Value, 'health_url', _('Адрес для проверки'),
			_('Небольшой HTTPS-ресурс, который открывается через каждый SOCKS-прокси.'));
		o.default = 'https://www.gstatic.com/generate_204';
		o.rmempty = false;
		o.validate = validateHttpUrl;

		o = s.taboption('uot', form.Flag, 'udp_over_tcp', _('Включить UDP over TCP'),
			_('TCP идёт через naive, UDP — через тот же туннель до приёмника на сервере. Ключи не нужны.'));
		o.default = '0';

		o = s.taboption('uot', form.DummyValue, '_server_cmd', _('Команда для сервера'),
			_('Выполните один раз на каждом внешнем сервере. Отражает сохранённые значения.'));
		o.depends('udp_over_tcp', '1');
		o.cfgvalue = function(sectionId) {
			return E('pre', {
				'style': 'white-space:pre-wrap;word-break:break-all;user-select:all;margin:0'
			}, uotServerCommand(uci.get('naive-orch', sectionId, 'uot_port') || '8389'));
		};

		o = s.taboption('uot', form.Value, 'uot_port', _('Порт приёмника'),
			_('Socks-приёмник на сервере. Порт 8388 занят legacy-приёмником для мобильных клиентов.'));
		o.datatype = 'port';
		o.default = '8389';
		o.depends('udp_over_tcp', '1');

		o = s.taboption('uot', form.Value, 'uot_offset', _('Смещение внутреннего порта'),
			_('Внутренний порт naive = SOCKS-порт + это значение.'));
		o.datatype = 'range(1,50000)';
		o.default = '1000';
		o.depends('udp_over_tcp', '1');

		/* ---------------- subscriptions: the primary setup path ---------------- */
		s = m.section(form.GridSection, 'subscription', _('Подписки'),
			_('Нажмите «Добавить», задайте понятное имя и вставьте URL. Затем нажмите «Сохранить и применить» внизу страницы и запустите обновление.'));
		s.addremove = true;
		s.anonymous = false;
		s.nodescriptions = true;
		s.sectiontitle = function(sectionId) {
			return uci.get('naive-orch', sectionId, 'label_prefix') || sectionId;
		};

		o = s.option(form.Flag, 'enabled', _('Вкл.'));
		o.default = '1';
		o.rmempty = false;

		o = s.option(form.Value, 'url', _('URL подписки'));
		o.rmempty = false;
		o.validate = validateHttpUrl;
		o.placeholder = 'https://example.com/subscription/token';

		o = s.option(form.Value, 'base_port', _('Первый SOCKS-порт'),
			_('Первый узел получит этот порт, следующие — +1, +2 и так далее.'));
		o.datatype = 'port';
		o.default = '1100';

		o = s.option(form.Flag, 'auto_update', _('Автообновление'));
		o.default = '1';

		o = s.option(form.Value, 'update_interval', _('Интервал, ч'),
			_('Как часто автоматически перечитывать подписку.'));
		o.datatype = 'range(1,8760)';
		o.default = '12';
		o.depends('auto_update', '1');

		o = s.option(form.Value, 'resolve', _('Подменить IP домена'),
			_('Необязательно. Аналог curl --resolve для панели за внутренним DNAT; TLS всё равно проверяется по домену URL.'));
		o.datatype = 'ipaddr';
		o.modalonly = true;

		o = s.option(form.Value, 'label_prefix', _('Префикс имён узлов'),
			_('Необязательно. По умолчанию используется имя секции подписки.'));
		o.modalonly = true;

		o = s.option(form.Value, 'concurrency', _('Параллельные соединения'),
			_('Необязательно. 0 оставляет настройку naive по умолчанию.'));
		o.datatype = 'uinteger';
		o.default = '0';
		o.modalonly = true;

		o = s.option(form.Button, '_update', _('Обновить'));
		o.inputtitle = _('Запустить');
		o.inputstyle = 'apply';
		o.onclick = function(event, sectionId) {
			return startSubscriptionUpdate(sectionId);
		};

		/* ---------------- manual nodes ---------------------------------------- */
		s = m.section(form.GridSection, 'node', _('Ручные узлы'),
			_('Используйте этот раздел только для узлов, которых нет в подписке.'));
		s.addremove = true;
		s.anonymous = true;
		s.filter = function(sectionId) {
			return !uci.get('naive-orch', sectionId, 'source');
		};

		o = s.option(form.Flag, 'enabled', _('Вкл.'));
		o.default = '1';

		o = s.option(form.Value, 'label', _('Название'));
		o.placeholder = _('Например, NL-1');

		o = s.option(form.Value, 'listen_port', _('SOCKS-порт'));
		o.datatype = 'port';
		o.rmempty = false;

		o = s.option(form.Value, 'proxy', _('Naive URL'),
			_('Формат: https://user:password@server:443'));
		o.rmempty = false;
		o.password = true;
		o.validate = validateNaiveProxy;

		o = s.option(form.Flag, 'padding', _('Padding'));
		o.modalonly = true;

		o = s.option(form.Value, 'concurrency', _('Параллельные соединения'));
		o.datatype = 'uinteger';
		o.modalonly = true;

		/* ---------------- imported nodes, deliberately read-only -------------- */
		s = m.section(form.GridSection, 'node', _('Импортированные узлы'),
			_('Этот список управляется подписками. Ручные изменения будут заменены при следующем обновлении.'));
		s.addremove = false;
		s.anonymous = true;
		s.filter = function(sectionId) {
			return !!uci.get('naive-orch', sectionId, 'source');
		};

		o = s.option(form.DummyValue, 'source', _('Подписка'));
		o.cfgvalue = function(sectionId) {
			return (uci.get('naive-orch', sectionId, 'source') || '').replace(/^sub:/, '');
		};
		o = s.option(form.DummyValue, 'label', _('Узел'));
		o = s.option(form.DummyValue, 'listen_port', _('SOCKS'));
		o.cfgvalue = function(sectionId) {
			return '127.0.0.1:' + (uci.get('naive-orch', sectionId, 'listen_port') || '');
		};
		o = s.option(form.DummyValue, 'proxy', _('Сервер'));
		o.cfgvalue = function(sectionId) {
			return maskProxy(uci.get('naive-orch', sectionId, 'proxy'));
		};

		return Promise.resolve(m.render()).then(function(rendered) {
			return E('div', {}, [
				E('div', { 'class': 'alert-message notice', 'style': 'margin-bottom:1em' }, [
					E('strong', {}, _('Быстрый старт: ')),
					_('добавьте подписку → сохраните настройки → откройте «Статус» и нажмите «Обновить все подписки».')
				]),
				rendered
			]);
		});
	}
});
__NAIVE_ORCH_FILE_11__

cd "$BUNDLE_DIR"
sh ./install.sh --enable "$@"
